FROM ubuntu:latest
RUN apt-get update && apt-get install -y build-essential git libboost-all-dev cmake libgmp3-dev pkg-config openssl libssl-dev
WORKDIR /usr/src/setup-tools
COPY . .
RUN mkdir build && cd build && cmake .. && make -j8
RUN ./build/test/setup_tests