FROM ubuntu:latest
RUN apt-get update && apt-get install -y build-essential cmake libgmp3-dev pkg-config libssl-dev
WORKDIR /usr/src/setup-tools
COPY . .
RUN mkdir build && cd build && cmake .. && make -j8
RUN ./build/test/setup_tests