#!/bin/bash

# Wait for other docker-composed stuff to startup. Ugh.
until curl --output /dev/null --silent --head --fail http://job-server; do
  echo "Waiting for job server to start..."
  sleep 1
done

[ -z "$NUMJOBS" ] && NUMJOBS=$(nproc)

echo "Running $NUMJOBS job processors."

for i in $(seq 1 $NUMJOBS)
do
   ./run-job &
done
wait