#!/bin/bash
cd /usr/src/setup-tools

while true; do
  JOBNUM=$(curl --retry 100 -L -s http://$JOB_SERVER_HOST/job)
  if [ -z "$JOBNUM" ]; then
    sleep $[RANDOM%10+1]
    continue
  fi
  echo Computing range polynomial $JOBNUM
  START=`date +%s`
  RESULT=$(./compute_range_polynomial ../setup_db $JOBNUM $NUMG1POINTS)
  if [ "$?" -ne 0 ]; then
    continue
  fi
  END=`date +%s`

  # Exit if ceremony changed or completed.
  STATE=$(curl --retry 100 -L -s http://$MPC_SERVER_HOST/api/state)
  NAME=$(echo $STATE | jq -j .name)
  CEREMONYSTATE=$(echo $STATE | jq -j .ceremonyState)
  if [ "$NAME" != "$CEREMONYNAME" ]; then
    echo "Ceremony name changed. Exiting."
    exit 0
  fi
  if [ "$CEREMONYSTATE" != "RANGE_PROOFS" ]; then
    echo "Ceremony state no longer RANGE_PROOFS. Exiting."
    exit 0
  fi

  if [ -n "$RESULT" ]; then
    curl --retry 100 -L -s -X PUT -d "$RESULT" -H "Content-Type: text/plain" http://$JOB_SERVER_HOST/complete/$JOBNUM > /dev/null
  fi
  echo "Job $JOBNUM complete in $((END-START))s: $RESULT"
done